version: '3.8'

services:
  app:
    build: .
    container_name: demo_crm
    depends_on:
      - mongo-db
    networks:
      - backend
      - frontend

  mongo-db:
    image: mongodb/mongodb-community-server
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - backend
    volumes:
      - db-data:/data/db

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./demo-crm-main/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  db-data:
