name: Demo_CRM CI/CD
# CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# CI
jobs:
  job1:
    name: CI - Unit Test
    runs-on: ubuntu-latest
    
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Install Runner updates
      - name: Install updates
        run: sudo apt-get update 

      # Install Yarn (use the official Yarn setup action)
      - name: Setup Yarn
        uses: borales/actions-yarn@v2.0.0

      # Install dependencies
      - name: Install dependencies
        run: sudo yarn install --frozen-lockfile

        
      # Change directory and build the application
      - name: Change directory and build
        run: |
          cd ./demo-crm-main
          sudo yarn build

      # Check if the application is up
      - name: Application check
        run: curl http://localhost:3000
