name: Demo_CRM CI/CD
#CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# CI
jobs:
  job1:
    name: CI - Unit Test
    # This workflow contains a single job called "build"
    runs-on: ubuntu-latest
    
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Install Runner updates
      - name: Install updates
        run: sudo apt-get update 

      # Run the appilcation demo_crm
      - name: Install yarn 
        run: sudo apt-get install -y yarn
        
      # Run application on Backround
      - name: Set working directory
        run: sudo yarn install --frozen-lockfile
        
      - name: Change directory and build
        run: |
              cd ./demo-crm-main
              sudo yarn build
                
      # Check if application is up
      - name: Application check
        run: curl http://localhost:3000

                    
        
        
