name: Demo_CRM CI/CD
# CI
# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# CI
jobs:
  job1:
    name: CI - Unit Test
    runs-on: ubuntu-latest
    
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install Runner updates
      - name: Install updates
        run: sudo apt-get update

      # Install Yarn
      - name: Install next
        run: sudo npm install next

      # run the application
      - name: Install next
        run: |
              cd ./demo-crm-main
              sudo npm run dev


      # Check if the application is up
      - name: Application check
        run: curl http://localhost:3000
